


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "BIT MnC alumni association",
//   description: "Generated by MnC students to connect with seniors",
// };

// export default function RootLayout({ children }) {
//   return (
   
//     <html lang="en">
      
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
//         <Navbar />
//         <main className="flex-1">{children}</main>
//         <Footer className="mt-auto" />
//       </body>
//     </html>
//   );
// }




import ClientLayout from "@/components/clientLayout";

export const metadata = {
  title: "BIT MnC Alumni Association",
  description: "Generated by MnC students to connect with seniors",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
